<a href="https://colab.research.google.com/github/datasigns-in/UpNiftyML/blob/main/Intraday_1mNifty50Downloader_RunDaily.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
from google.colab import drive
import urllib.parse
import pandas as pd
import pytz,os
import requests
import json ,requests
from  datetime import datetime,timedelta,time
TIME_ZONE = pytz.timezone('Asia/Kolkata')

In [2]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')


# Get today's date
today_date = datetime.now().strftime("%Y-%m-%d")

# Get today's date as a string.
today_str = datetime.now().strftime("%Y%m%d")

# Create the folder path
folder_path = f'/content/drive/MyDrive/Nifty50DataAutoUpstox/1m_6mFrom17032024/{today_date}'

# Create the folder if it doesn't exist
if not os.path.exists(folder_path):
  !mkdir -p "{folder_path}"

fileUrl ='https://assets.upstox.com/market-quote/instruments/exchange/complete.csv.gz'
symboldf = pd.read_csv(fileUrl)
nifty50 = symboldf.iloc[:1]
nifty50.tradingsymbol = "Nifty50"
nvix = symboldf.iloc[35:36]
nvix.tradingsymbol = "NVIX"
#symboldf['expiry'] = pd.to_datetime(symboldf['expiry']).apply(lambda x: x.date())
#symboldf = symboldf[symboldf.exchange == 'NSE_EQ']
eqCsv = pd.read_csv('/content/drive/MyDrive/Nifty50DataAutoUpstox/NIFTY50NSE.csv')
isinList = 'NSE_EQ|' + eqCsv[' ISIN NUMBER']
symboldf = symboldf[symboldf.instrument_key.isin(isinList)]

symboldf = symboldf.concat(nifty50)
symboldf = symboldf.concat(nvix)
symboldf

Mounted at /content/drive

<ipython-input-2-31c4edcf34b8>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nifty50.tradingsymbol = "Nifty50"
<ipython-input-2-31c4edcf34b8>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nvix.tradingsymbol = "NVIX"
<ipython-input-2-31c4edcf34b8>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  symboldf = symboldf.append(nifty50)
<ipython-input-2-31c4edcf34b8>:32: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  symboldf = symboldf.append(nvix)

,instrument_key,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,option_type,exchange
3023,NSE_EQ|INE423A01024,25.0,ADANIENT,ADANI ENTERPRISES LIMITED,3132.20,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3025,NSE_EQ|INE742F01042,15083.0,ADANIPORTS,ADANI PORT & SEZ LTD,1283.00,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3121,NSE_EQ|INE437A01024,157.0,APOLLOHOSP,APOLLO HOSPITALS ENTER. L,5983.20,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3163,NSE_EQ|INE021A01026,236.0,ASIANPAINT,ASIAN PAINTS LIMITED,2867.55,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3206,NSE_EQ|INE238A01034,5900.0,AXISBANK,AXIS BANK LIMITED,1046.40,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3226,NSE_EQ|INE917I01010,16669.0,BAJAJ-AUTO,BAJAJ AUTO LIMITED,8350.70,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3229,NSE_EQ|INE918I01026,16675.0,BAJAJFINSV,BAJAJ FINSERV LTD.,1571.45,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3234,NSE_EQ|INE296A01024,317.0,BAJFINANCE,BAJAJ FINANCE LIMITED,6514.35,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3302,NSE_EQ|INE397D01024,10604.0,BHARTIARTL,BHARTI AIRTEL LIMITED,1220.00,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3334,NSE_EQ|INE029A01011,526.0,BPCL,BHARAT PETROLEUM CORP LT,586.45,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3367,NSE_EQ|INE216A01030,547.0,BRITANNIA,BRITANNIA INDUSTRIES LTD,4974.20,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3475,NSE_EQ|INE059A01026,694.0,CIPLA,CIPLA LTD,1488.05,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3486,NSE_EQ|INE522F01014,20374.0,COALINDIA,COAL INDIA LTD,415.25,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3624,NSE_EQ|INE361B01024,10940.0,DIVISLAB,DIVI S LABORATORIES LTD,3485.40,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3650,NSE_EQ|INE089A01023,881.0,DRREDDY,DR. REDDY S LABORATORIES,6284.90,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3679,NSE_EQ|INE066A01021,910.0,EICHERMOT,EICHER MOTORS LTD,3745.65,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
3900,NSE_EQ|INE047A01021,1232.0,GRASIM,GRASIM INDUSTRIES LTD,2197.10,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4059,NSE_EQ|INE860A01027,7229.0,HCLTECH,HCL TECHNOLOGIES LTD,1647.30,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4085,NSE_EQ|INE040A01034,1333.0,HDFCBANK,HDFC BANK LTD,1452.65,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4090,NSE_EQ|INE795G01014,467.0,HDFCLIFE,HDFC LIFE INS CO LTD,632.35,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4121,NSE_EQ|INE158A01026,1348.0,HEROMOTOCO,HERO MOTOCORP LIMITED,4585.30,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4144,NSE_EQ|INE038A01020,1363.0,HINDALCO,HINDALCO INDUSTRIES LTD,532.55,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4152,NSE_EQ|INE030A01027,1394.0,HINDUNILVR,HINDUSTAN UNILEVER LTD.,2327.70,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4404,NSE_EQ|INE090A01021,4963.0,ICICIBANK,ICICI BANK LTD.,1080.35,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4538,NSE_EQ|INE095A01012,5258.0,INDUSINDBK,INDUSIND BANK LIMITED,1484.35,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4547,NSE_EQ|INE009A01021,1594.0,INFY,INFOSYS LIMITED,1634.00,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4616,NSE_EQ|INE154A01025,1660.0,ITC,ITC LTD,419.10,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4682,NSE_EQ|INE019A01038,11723.0,JSWSTEEL,JSW STEEL LIMITED,780.65,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4767,NSE_EQ|INE237A01028,1922.0,KOTAKBANK,KOTAK MAHINDRA BANK LTD,1738.30,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4888,NSE_EQ|INE018A01030,11483.0,LT,LARSEN & TOUBRO LTD.,3537.15,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4891,NSE_EQ|INE214T01019,17818.0,LTIM,LTIMINDTREE LIMITED,5194.35,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4900,NSE_EQ|INE101A01026,2031.0,M&M,MAHINDRA & MAHINDRA LTD,1799.50,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
4962,NSE_EQ|INE585B01010,10999.0,MARUTI,MARUTI SUZUKI INDIA LTD.,11476.65,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
5143,NSE_EQ|INE239A01024,17963.0,NESTLEIND,NESTLE INDIA LIMITED,2603.65,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
5245,NSE_EQ|INE733E01010,11630.0,NTPC,NTPC LTD,316.30,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
5282,NSE_EQ|INE213A01029,2475.0,ONGC,OIL AND NATURAL GAS CORP.,258.75,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
5425,NSE_EQ|INE752E01010,14977.0,POWERGRID,POWER GRID CORP. LTD.,265.95,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
5556,NSE_EQ|INE002A01018,2885.0,RELIANCE,RELIANCE INDUSTRIES LTD,2836.45,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
5680,NSE_EQ|INE123W01016,21808.0,SBILIFE,SBI LIFE INSURANCE CO LTD,1500.00,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
5681,NSE_EQ|INE062A01020,3045.0,SBIN,STATE BANK OF INDIA,731.90,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6038,NSE_EQ|INE044A01036,3351.0,SUNPHARMA,SUN PHARMACEUTICAL IND L,1548.20,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6113,NSE_EQ|INE192A01025,3432.0,TATACONSUM,TATA CONSUMER PRODUCT LTD,1212.15,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6117,NSE_EQ|INE155A01022,3456.0,TATAMOTORS,TATA MOTORS LIMITED,945.85,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6120,NSE_EQ|INE081A01020,3499.0,TATASTEEL,TATA STEEL LIMITED,141.70,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6132,NSE_EQ|INE467B01029,11536.0,TCS,TATA CONSULTANCY SERV LT,4219.25,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6138,NSE_EQ|INE669C01036,13538.0,TECHM,TECH MAHINDRA LIMITED,1282.20,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6179,NSE_EQ|INE280A01028,3506.0,TITAN,TITAN COMPANY LIMITED,3633.20,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6262,NSE_EQ|INE481G01011,11532.0,ULTRACEMCO,ULTRATECH CEMENT LIMITED,9632.95,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6282,NSE_EQ|INE628A01036,11287.0,UPL,UPL LIMITED,475.15,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
6437,NSE_EQ|INE075A01022,3787.0,WIPRO,WIPRO LTD,517.00,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
0,NSE_INDEX|Nifty 50,17.0,Nifty50,Nifty 50,22023.35,NaN,NaN,NaN,NaN,INDEX,NaN,NSE_INDEX
35,NSE_INDEX|India VIX,43.0,NVIX,India VIX,13.69,NaN,NaN,NaN,NaN,INDEX,NaN,NSE_INDEX

In [ ]:
#fromDate = (datetime.now(TIME_ZONE)  - timedelta(days=10000)) .strftime("%Y-%m-%d")
#fromDate

In [3]:
def getHistoricalData(symInfo):
    res = None
    try:
        parseInstrument = urllib.parse.quote(symInfo.instrument_key)
        fromDate = (datetime.now(TIME_ZONE)  - timedelta(days=1)) .strftime("%Y-%m-%d")
        todate = datetime.now(TIME_ZONE).strftime("%Y-%m-%d")
        url = f'https://api.upstox.com/v2/historical-candle/intraday/{parseInstrument}/1minute'
        #print(url)

        res = requests.get(url,headers={'accept': 'application/json',},params={},timeout=5.0)
        candleRes = res.json()

        if 'data' in candleRes and 'candles' in candleRes['data'] and  candleRes['data']['candles']:
            candleData = pd.DataFrame(candleRes['data']['candles'])
            candleData.columns = ['date','open','high','low', 'close','vol','oi']
            candleData['date'] = pd.to_datetime(candleData['date']).dt.tz_convert('Asia/Kolkata')
            candleData['symbol'] = symInfo.tradingsymbol
            print(symInfo.tradingsymbol, len(candleData))
            return candleData
        else:
            print('No data',symInfo.instrument_key, candleRes)
    except :
        print(f'Error in data fetch for {symInfo.instrument_key} {res} {e}')

In [4]:
getHistoricalData(symboldf.iloc[50])

Nifty50 375

,date,open,high,low,close,vol,oi,symbol
0,2024-03-18 15:29:00+05:30,22057.90,22057.90,22050.15,22051.50,0,0,Nifty50
1,2024-03-18 15:28:00+05:30,22052.55,22061.20,22051.00,22057.65,0,0,Nifty50
2,2024-03-18 15:27:00+05:30,22048.90,22055.30,22048.90,22052.60,0,0,Nifty50
3,2024-03-18 15:26:00+05:30,22052.35,22052.70,22047.05,22047.95,0,0,Nifty50
4,2024-03-18 15:25:00+05:30,22048.65,22054.00,22048.65,22050.80,0,0,Nifty50
...,...,...,...,...,...,...,...,...
370,2024-03-18 09:19:00+05:30,22004.30,22019.65,22004.30,22007.90,0,0,Nifty50
371,2024-03-18 09:18:00+05:30,21986.90,22009.65,21986.85,22002.80,0,0,Nifty50
372,2024-03-18 09:17:00+05:30,21983.80,21988.20,21971.60,21987.25,0,0,Nifty50
373,2024-03-18 09:16:00+05:30,21958.00,21984.75,21953.70,21984.40,0,0,Nifty50
374,2024-03-18 09:15:00+05:30,21990.10,22009.55,21954.35,21955.35,0,0,Nifty50

In [5]:
candledfList = []
for i in symboldf.index:
    res = getHistoricalData(symboldf.loc[i])
    if res is not None: candledfList.append(res)

ADANIENT 375
ADANIPORTS 375
APOLLOHOSP 375
ASIANPAINT 375
AXISBANK 375
BAJAJ-AUTO 375
BAJAJFINSV 375
BAJFINANCE 375
BHARTIARTL 375
BPCL 375
BRITANNIA 375
CIPLA 375
COALINDIA 375
DIVISLAB 375
DRREDDY 375
EICHERMOT 375
GRASIM 375
HCLTECH 375
HDFCBANK 375
HDFCLIFE 375
HEROMOTOCO 375
HINDALCO 375
HINDUNILVR 375
ICICIBANK 375
INDUSINDBK 375
INFY 375
ITC 375
JSWSTEEL 375
KOTAKBANK 375
LT 375
LTIM 375
M&M 375
MARUTI 375
NESTLEIND 375
NTPC 375
ONGC 375
POWERGRID 375
RELIANCE 375
SBILIFE 375
SBIN 375
SUNPHARMA 375
TATACONSUM 375
TATAMOTORS 375
TATASTEEL 375
TCS 375
TECHM 375
TITAN 375
ULTRACEMCO 375
UPL 375
WIPRO 375
Nifty50 375
NVIX 375

In [6]:
finalDataDf = pd.concat(candledfList,ignore_index= True)
finalDataDf

,date,open,high,low,close,vol,oi,symbol
0,2024-03-18 15:29:00+05:30,3110.00,3112.00,3108.00,3110.00,4326,0,ADANIENT
1,2024-03-18 15:28:00+05:30,3108.65,3110.00,3108.00,3108.95,6127,0,ADANIENT
2,2024-03-18 15:27:00+05:30,3109.00,3110.00,3108.00,3108.75,9057,0,ADANIENT
3,2024-03-18 15:26:00+05:30,3110.50,3112.05,3108.00,3108.40,22809,0,ADANIENT
4,2024-03-18 15:25:00+05:30,3112.70,3113.30,3110.00,3110.65,19959,0,ADANIENT
...,...,...,...,...,...,...,...,...
19495,2024-03-18 09:19:00+05:30,14.47,14.48,14.43,14.44,0,0,NVIX
19496,2024-03-18 09:18:00+05:30,14.49,14.49,14.40,14.47,0,0,NVIX
19497,2024-03-18 09:17:00+05:30,14.56,14.56,14.48,14.49,0,0,NVIX
19498,2024-03-18 09:16:00+05:30,14.49,14.62,14.49,14.56,0,0,NVIX
19499,2024-03-18 09:15:00+05:30,13.69,14.53,13.69,14.47,0,0,NVIX

In [7]:
# prompt: upload this dataset to google drive

#from google.colab import drive
#drive.mount('/content/drive')

finalDataDf.to_csv(f'{folder_path}/finalDataDf_{today_str}.csv')

In [8]:
isCsv = True
for symData in candledfList:
    try:
        filename = symData.iloc[0]['symbol']
        if isCsv :
            filename = f'{filename}_{today_str}.csv'
            symData.to_csv(f'{folder_path}/{filename}',index=False)
        else:
            filename = f'{filename}.parquet'
            symData.to_parquet(filename , engine='pyarrow')
    except Exception as e:
        print(f'Error {e}')

In [ ]:
pd.read_parquet('C:\\Users\\eqEOD\\20MICRONS.parquet')

In [9]:
# prompt: parse candledfList first array as json

import json
import pandas as pd

candledfList_json = []
for i in symboldf.index:
    res = getHistoricalData(symboldf.loc[i])
    if res is not None: candledfList_json.append(json.dumps(res.to_dict(orient='records'), default=lambda x: x.strftime('%Y-%m-%d %H:%M:%S') if isinstance(x, pd.Timestamp) else x))

#candledfList_json = json.dumps(candledfList[0].to_dict(orient='records'), default=lambda x: x.strftime('%Y-%m-%d %H:%M:%S') if isinstance(x, pd.Timestamp) else x)

ADANIENT 375
ADANIPORTS 375
APOLLOHOSP 375
ASIANPAINT 375
AXISBANK 375
BAJAJ-AUTO 375
BAJAJFINSV 375
BAJFINANCE 375
BHARTIARTL 375
BPCL 375
BRITANNIA 375
CIPLA 375
COALINDIA 375
DIVISLAB 375
DRREDDY 375
EICHERMOT 375
GRASIM 375
HCLTECH 375
HDFCBANK 375
HDFCLIFE 375
HEROMOTOCO 375
HINDALCO 375
HINDUNILVR 375
ICICIBANK 375
INDUSINDBK 375
INFY 375
ITC 375
JSWSTEEL 375
KOTAKBANK 375
LT 375
LTIM 375
M&M 375
MARUTI 375
NESTLEIND 375
NTPC 375
ONGC 375
POWERGRID 375
RELIANCE 375
SBILIFE 375
SBIN 375
SUNPHARMA 375
TATACONSUM 375
TATAMOTORS 375
TATASTEEL 375
TCS 375
TECHM 375
TITAN 375
ULTRACEMCO 375
UPL 375
WIPRO 375
Nifty50 375
NVIX 375

In [10]:
# prompt: upload all different json to google drive path /content/drive/MyDrive/Nifty50DataAutoUpstox/1m_6mFrom17032024/json

for i, candledf_json in enumerate(candledfList_json):
    filename = f'{folder_path}/{symboldf.iloc[i]["tradingsymbol"]}_{today_str}.json'
    with open(filename, 'w') as f:
        f.write(candledf_json)